name: CD

on:
  workflow_run:
    workflows: [CI]
    types: [completed]
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Deploy sur la VM
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/app
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ secrets.VM_USER }} --password-stdin
            docker compose pull app
            docker compose up -d --no-deps app
